import { Header } from "./Header/Header";
import { Footer } from "./Footer/Footer";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState, useRef } from "react";

import { motion, AnimatePresence } from "framer-motion"
import gsap from "gsap";

import ScrollTrigger from "gsap/dist/ScrollTrigger";
import loadingImage from '../public/imgs/Infinity-1s-200px.svg'
import Image from "next/image";
import { LocomotiveScrollProvider } from "react-locomotive-scroll";



export const Base = (props) => {
  // console.log(props)
  const containerRef = useRef(null)
  const [loading, isLoading] = useState(false)
  const router = useRouter()

  useEffect(()=>{

    router.events.on('routeChangeStart', (url, { shallow }) => {
      console.log(url == router.asPath)
      if (router.asPath != url){
        isLoading(true)

      }
    });
    router.events.on('routeChangeComplete', (url, { shallow }) => {
      isLoading(false)
      
          
    });
    
  },[])
  
  
  const handleComplete = ()=>{

  }
  return (
    <>

    
    <Head>
      <title>OKHUB</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/imgs/logo.svg" />
    </Head>
    
    {
            loading && (
            <motion.div 
            key={'loading-section'}
            className="loading-section"
            initial={{opacity:0}}
            animate={{opacity:1}}
            exit={{opacity:0}}
            onAnimationComplete={handleComplete}

            >
              <Image src={loadingImage} alt='' />
            </motion.div>

            )
          }
          <Header/>
    
            {props.children}
          
          <Footer/>
   
 
    </>
  );
};
