import Head from "next/head"
import loadingImage from '../public/imgs/Infinity-1s-200px.svg'
import { motion, AnimatePresence } from "framer-motion"
import Image from "next/image"

import { HeaderMobile } from "./Header/HeaderMobile"
import { FooterMobile } from "./Footer/FooterMobile"
import { useEffect, useState } from "react"
import { useRouter } from "next/router"

export const BaseMobile = (props)=>{

    const router= useRouter()
    const [loading, isLoading] = useState(false)
    useEffect(()=>{
      router.events.on('routeChangeStart', (url, { shallow }) => {   
        if (router.asPath != url  && !url.includes('?')){
          isLoading(true)
        }
      });
      router.events.on('routeChangeComplete', (url, { shallow }) => {
        isLoading(false)    
      });
      
    },[])
    
    return (
        <>
             <Head>
            <title>OKHUB</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/imgs/logo.svg" />
            </Head>

            {
            loading && (
            <motion.div 
            key={'loading-section'}
            className="loading-section"
            initial={{opacity:0}}
            animate={{opacity:1}}
            exit={{opacity:0}}
            // onAnimationComplete={handleComplete}

            >
                <Image src={loadingImage} alt='' />
            </motion.div>

            )
            }

            <HeaderMobile/>
            {props.children}

            <FooterMobile/>



            
        </>
    )
}